-- LABORATORIO IOT
DROP DATABASE IF EXISTS LABORATORIO_IOT;
CREATE DATABASE LABORATORIO_IOT;
USE LABORATORIO_IOT;


CREATE TABLE ROL (
    ID_ROL INT NOT NULL,
    NOMBRE_ROL VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION TEXT
)
ENGINE = INNODB;

CREATE TABLE PERMISO(
  ID_PERMISO INT NOT NULL,
  NOMBRE_PERMISO VARCHAR(45) NOT NULL,
  ESTADO_PERMISO TINYINT NOT NULL DEFAULT 1
  )
ENGINE = InnoDB;

CREATE TABLE PERMISO_ROL (
  ID_PERMISO_ROL INT NOT NULL,
  FECHA_PERMISO_ROL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ESTADO_PERMISO_ROL TINYINT NOT NULL DEFAULT 1,
  FK_ID_PERMISO INT NOT NULL,
  FK_ID_ROL INT NOT NULL
  )
ENGINE = InnoDB;


CREATE TABLE USUARIO (
    ID_USUARIO INT NOT NULL,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL, -- SE GUARDA HASH CON BCRYPT
    EMAIL VARCHAR(100) UNIQUE,
    FK_ID_ROL INT NOT NULL,
    CREADO_EN_USUARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
ENGINE = INNODB;

CREATE TABLE ESTADO_LABORATORIO (
    ID_ESTADO_LABORATORIO INT NOT NULL,
    NOMBRE_ESTADO_LABORATORIO VARCHAR(50) NOT NULL UNIQUE
)
ENGINE = INNODB;

CREATE TABLE TIPO_ALERTA (
    ID_TIPO_ALERTA INT NOT NULL,
    NOMBRE_TIPO_ALERTA VARCHAR(50) NOT NULL UNIQUE
)
ENGINE = INNODB;

CREATE TABLE LABORATORIO (
    ID_LABORATORIO INT NOT NULL,
    NOMBRE_LABORATORIO VARCHAR(100) NOT NULL,
    DESCRIPCION_LABORATORIO TEXT,
    PK_ID_ESTADO_LABORATORIO INT NOT NULL
)
ENGINE = INNODB;

CREATE TABLE USUARIO_LABORATORIO (
    ID_USUARIO_LABORATORIO INT NOT NULL,
	CREADO_EN_USUARIO_LABORATORIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FK_ID_USUARIO INT NOT NULL,
    FK_ID_LABORATORIO INT NOT NULL,
    UNIQUE(FK_ID_USUARIO, FK_ID_LABORATORIO)
)
ENGINE = INNODB;

CREATE TABLE MODULO (
    ID_MODULO INT NOT NULL,
    NOMBRE_MODULO VARCHAR(100) NOT NULL,
    FK_ID_LABORATORIO INT NOT NULL,    
    CREADO_EN_MODULO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE = INNODB;

CREATE TABLE PROYECTO (
    ID_PROYECTO INT NOT NULL,
    NOMBRE_PROYECTO VARCHAR(100) NOT NULL,
    FK_ID_MODULO INT NOT NULL,    
    CREADO_EN TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ESPACIO_TRABAJO (
    ID_ESPACIO_TRABAJO INT NOT NULL,
    NOMBRE_ESPACIO_TRABAJO INT NOT NULL,
    DESCRIPCION_ESPACIO_TRABAJO VARCHAR(100),
    FK_ID_PROYECTO INT NOT NULL,    
    CREADO_EN_ESPACIO_TRABAJO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
ENGINE = INNODB;

CREATE TABLE ESTADO_DISPOSITIVO (
    ID_ESTADO_DISPOSITIVO INT NOT NULL,
    NOMBRE_ESTADO_DISPOSITIVO VARCHAR(50) NOT NULL UNIQUE -- HABILITADO, INHABILITADO, MANTENIMIENTO
)
ENGINE = INNODB;

CREATE TABLE TIPO_SENSOR (
    ID_TIPO_SENSOR INT NOT NULL,
    NOMBRE_TIPO_SENSOR VARCHAR(50) NOT NULL UNIQUE
)
ENGINE = INNODB;

CREATE TABLE SENSOR (
    ID_SENSOR INT NOT NULL,
    NOMBRE_SENSOR VARCHAR(100) NOT NULL,  
    UNIDAD_SENSOR VARCHAR(20), -- °C, %, ETC.
	FK_ID_ESTADO_DISPOSITIVO INT NOT NULL,
    FK_ID_ESPACIO_TRABAJO INT NOT NULL,
	FK_ID_TIPO_SENSOR INT NOT NULL, -- TEMPERATURA, HUMEDAD, ETC.
    CREADO_EN_SENSOR TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
ENGINE = INNODB;


CREATE TABLE TIPO_ACTUADOR (
ID_TIPO_ACTUADOR INT NOT NULL,
NOMBRE_TIPO_ACTUADOR VARCHAR(50) NOT NULL UNIQUE
)
ENGINE = INNODB;

CREATE TABLE ACTUADOR (
    ID_ACTUADOR INT NOT NULL,
    NOMBRE_ACTUADOR VARCHAR(100) NOT NULL,
	FK_ID_TIPO_ACTUADOR INT NOT NULL,    
	FK_ID_ESTADO_DISPOSITIVO INT NOT NULL,
    FK_ID_ESPACIO_TRABAJO INT NOT NULL NOT NULL,
    CREADO_EN_ACTUADOR TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FK_ID_HORARIO_AUTOMATIZACION INT NULL
)
ENGINE = INNODB;

CREATE TABLE ALERTA (
    ID_ALERTA INT NOT NULL,
    FK_ID_LABORATORIO INT NOT NULL,
    MENSAJE_ALERTA TEXT NOT NULL,
    FK_ID_TIPO_ALERTA INT NOT NULL,
	FK_ID_SENSOR INT NOT NULL,
    CREADA_EN_ALERTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
ENGINE = INNODB;

CREATE TABLE ETAPA_CRECIMIENTO (
    ID_ETAPA_CRECIMIENTO INT NOT NULL,
    FK_ID_ESPACIO_TRABAJO INT NOT NULL,
    NOMBRE_ETAPA_CRECIMIENTO VARCHAR(50) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE
    -- DURACION_DIAS INT GENERATED ALWAYS AS (DATE_PART('DAY', FECHA_FIN - FECHA_INICIO)) STORED
)
ENGINE = INNODB;


CREATE TABLE LECTURA (
    ID_LECTURA INT NOT NULL,
    FK_ID_SENSOR INT NOT NULL,
    VALOR_LECTURA NUMERIC(10,2) NOT NULL,
    REGISTRADO_EN_LECTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
ENGINE = INNODB;

CREATE TABLE CAMARA (
    ID_CAMARA INT NOT NULL,
    NOMBRE_CAMARA VARCHAR(100) NOT NULL,
    URL_STREAM VARCHAR(255),
    FK_ID_LABORATORIO INT NOT NULL,
    ESTADO_CAMARA BOOLEAN DEFAULT TRUE,
    CREADO_EN_CAMARA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
ENGINE = INNODB;

CREATE TABLE CONTROLADOR_AIRE (
    ID_CONTROLADOR_AIRE INT NOT NULL,
    NOMBRE_CONTROLADOR_AIRE VARCHAR(100) NOT NULL,
    TEMPERATURA_OBJETIVO_CONTROLADOR_AIRE NUMERIC(5,2),
    ESTADO_CONTROLADOR_AIRE BOOLEAN DEFAULT FALSE,
    FK_ID_LABORATORIO INT NOT NULL NOT NULL,
    CREADO_EN_CONTROLADOR_AIRE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FK_ID_HORARIO_AUTOMATIZACION INT NULL
)
ENGINE = INNODB;

CREATE TABLE HORARIO_AUTOMATIZACION (
    ID_HORARIO_AUTOMATIZACION INT NOT NULL,
    HORA_INICIO_HORARIO_AUTOMATIZACION TIME NOT NULL,
    HORA_FIN_HORARIO_AUTOMATIZACION TIME NOT NULL,
    DIAS_SEMANA_HORARIO_AUTOMATIZACION VARCHAR(7), -- LMXJVSD FORMATO
    ESTADO_HORARIO_AUTOMATIZACION BOOLEAN DEFAULT TRUE,
    CREADO_EN_HORARIO_AUTOMATIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
ENGINE = INNODB;

-- LLAVES PRIMARIAS
ALTER TABLE ROL ADD CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL);
ALTER TABLE PERMISO ADD CONSTRAINT PK_PERMISO PRIMARY KEY (ID_PERMISO);
ALTER TABLE PERMISO_ROL ADD CONSTRAINT PK_PERMISO_ROL PRIMARY KEY (ID_PERMISO_ROL);
ALTER TABLE USUARIO ADD CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO);
ALTER TABLE ESTADO_LABORATORIO ADD CONSTRAINT PK_ESTADO_LABORATORIO PRIMARY KEY (ID_ESTADO_LABORATORIO);
ALTER TABLE TIPO_ALERTA ADD CONSTRAINT PK_TIPO_ALERTA PRIMARY KEY (ID_TIPO_ALERTA);
ALTER TABLE LABORATORIO ADD CONSTRAINT PK_LABORATORIO PRIMARY KEY (ID_LABORATORIO);
ALTER TABLE USUARIO_LABORATORIO ADD CONSTRAINT PK_USUARIO_LABORATORIO PRIMARY KEY (ID_USUARIO_LABORATORIO);
ALTER TABLE MODULO ADD CONSTRAINT PK_MODULO PRIMARY KEY (ID_MODULO);
ALTER TABLE PROYECTO ADD CONSTRAINT PK_PROYECTO PRIMARY KEY (ID_PROYECTO);
ALTER TABLE ESPACIO_TRABAJO ADD CONSTRAINT PK_ESPACIO_TRABAJO PRIMARY KEY (ID_ESPACIO_TRABAJO);
ALTER TABLE ESTADO_DISPOSITIVO ADD CONSTRAINT PK_ESTADO_DISPOSITIVO PRIMARY KEY (ID_ESTADO_DISPOSITIVO);
ALTER TABLE TIPO_SENSOR ADD CONSTRAINT PK_TIPO_SENSOR PRIMARY KEY (ID_TIPO_SENSOR);
ALTER TABLE SENSOR ADD CONSTRAINT PK_SENSOR PRIMARY KEY (ID_SENSOR);
ALTER TABLE TIPO_ACTUADOR ADD CONSTRAINT PK_TIPO_ACTUADOR PRIMARY KEY (ID_TIPO_ACTUADOR);
ALTER TABLE ACTUADOR ADD CONSTRAINT PK_ACTUADOR PRIMARY KEY (ID_ACTUADOR);
ALTER TABLE ALERTA ADD CONSTRAINT PK_ALERTA PRIMARY KEY (ID_ALERTA);
ALTER TABLE ETAPA_CRECIMIENTO ADD CONSTRAINT PK_ETAPA_CRECIMIENTO PRIMARY KEY (ID_ETAPA_CRECIMIENTO);
ALTER TABLE LECTURA ADD CONSTRAINT PK_LECTURA PRIMARY KEY (ID_LECTURA);
ALTER TABLE CAMARA ADD CONSTRAINT PK_CAMARA PRIMARY KEY (ID_CAMARA);
ALTER TABLE CONTROLADOR_AIRE ADD CONSTRAINT PK_CONTROLADOR_AIRE PRIMARY KEY (ID_CONTROLADOR_AIRE);
ALTER TABLE HORARIO_AUTOMATIZACION ADD CONSTRAINT PK_HORARIO_AUTOMATIZACION PRIMARY KEY (ID_HORARIO_AUTOMATIZACION);

-- AUTO INCREMENTS
ALTER TABLE ROL MODIFY ID_ROL INT AUTO_INCREMENT;
ALTER TABLE PERMISO MODIFY ID_PERMISO INT AUTO_INCREMENT;
ALTER TABLE PERMISO_ROL MODIFY ID_PERMISO_ROL INT AUTO_INCREMENT;
ALTER TABLE USUARIO MODIFY ID_USUARIO INT AUTO_INCREMENT;
ALTER TABLE ESTADO_LABORATORIO MODIFY ID_ESTADO_LABORATORIO INT AUTO_INCREMENT;
ALTER TABLE TIPO_ALERTA MODIFY ID_TIPO_ALERTA INT AUTO_INCREMENT;
ALTER TABLE LABORATORIO MODIFY ID_LABORATORIO INT AUTO_INCREMENT;
ALTER TABLE USUARIO_LABORATORIO MODIFY ID_USUARIO_LABORATORIO INT AUTO_INCREMENT;
ALTER TABLE MODULO MODIFY ID_MODULO INT AUTO_INCREMENT;
ALTER TABLE PROYECTO MODIFY ID_PROYECTO INT AUTO_INCREMENT;
ALTER TABLE ESPACIO_TRABAJO MODIFY ID_ESPACIO_TRABAJO INT AUTO_INCREMENT;
ALTER TABLE ESTADO_DISPOSITIVO MODIFY ID_ESTADO_DISPOSITIVO INT AUTO_INCREMENT;
ALTER TABLE TIPO_SENSOR MODIFY ID_TIPO_SENSOR INT AUTO_INCREMENT;
ALTER TABLE SENSOR MODIFY ID_SENSOR INT AUTO_INCREMENT;
ALTER TABLE TIPO_ACTUADOR MODIFY ID_TIPO_ACTUADOR INT AUTO_INCREMENT;
ALTER TABLE ACTUADOR MODIFY ID_ACTUADOR INT AUTO_INCREMENT;
ALTER TABLE ALERTA MODIFY ID_ALERTA INT AUTO_INCREMENT;
ALTER TABLE ETAPA_CRECIMIENTO MODIFY ID_ETAPA_CRECIMIENTO INT AUTO_INCREMENT;
ALTER TABLE LECTURA MODIFY ID_LECTURA INT AUTO_INCREMENT;
ALTER TABLE CAMARA MODIFY ID_CAMARA INT AUTO_INCREMENT;
ALTER TABLE CONTROLADOR_AIRE MODIFY ID_CONTROLADOR_AIRE INT AUTO_INCREMENT;
ALTER TABLE HORARIO_AUTOMATIZACION MODIFY ID_HORARIO_AUTOMATIZACION INT AUTO_INCREMENT;

-- LLAVES FORÁNEAS
ALTER TABLE PERMISO_ROL ADD CONSTRAINT FK_PERMISO_ROL_PERMISO FOREIGN KEY (FK_ID_PERMISO) REFERENCES PERMISO (ID_PERMISO);
ALTER TABLE PERMISO_ROL ADD CONSTRAINT FK_PERMISO_ROL_ROL FOREIGN KEY (FK_ID_ROL) REFERENCES ROL (ID_ROL);
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (FK_ID_ROL) REFERENCES ROL (ID_ROL);
ALTER TABLE LABORATORIO ADD CONSTRAINT FK_LABORATORIO_ESTADO FOREIGN KEY (PK_ID_ESTADO_LABORATORIO) REFERENCES ESTADO_LABORATORIO (ID_ESTADO_LABORATORIO);
ALTER TABLE USUARIO_LABORATORIO ADD CONSTRAINT FK_USUARIO_LABORATORIO_USUARIO FOREIGN KEY (FK_ID_USUARIO) REFERENCES USUARIO (ID_USUARIO);
ALTER TABLE USUARIO_LABORATORIO ADD CONSTRAINT FK_USUARIO_LABORATORIO_LABORATORIO FOREIGN KEY (FK_ID_LABORATORIO) REFERENCES LABORATORIO (ID_LABORATORIO);
ALTER TABLE MODULO ADD CONSTRAINT FK_MODULO_LABORATORIO FOREIGN KEY (FK_ID_LABORATORIO) REFERENCES LABORATORIO (ID_LABORATORIO);
ALTER TABLE PROYECTO ADD CONSTRAINT FK_MODULO FOREIGN KEY (FK_ID_MODULO) REFERENCES MODULO (ID_MODULO);
ALTER TABLE ESPACIO_TRABAJO ADD CONSTRAINT FK_ESPACIO_TRABAJO_PROYECTO FOREIGN KEY (FK_ID_PROYECTO) REFERENCES PROYECTO (ID_PROYECTO);
ALTER TABLE SENSOR ADD CONSTRAINT FK_SENSOR_ESTADO FOREIGN KEY (FK_ID_ESTADO_DISPOSITIVO) REFERENCES ESTADO_DISPOSITIVO (ID_ESTADO_DISPOSITIVO);
ALTER TABLE SENSOR ADD CONSTRAINT FK_SENSOR_ESPACIO_TRABAJO FOREIGN KEY (FK_ID_ESPACIO_TRABAJO) REFERENCES ESPACIO_TRABAJO (ID_ESPACIO_TRABAJO);
ALTER TABLE SENSOR ADD CONSTRAINT FK_SENSOR_TIPO FOREIGN KEY (FK_ID_TIPO_SENSOR) REFERENCES TIPO_SENSOR (ID_TIPO_SENSOR);
ALTER TABLE ACTUADOR ADD CONSTRAINT FK_ACTUADOR_TIPO FOREIGN KEY (FK_ID_TIPO_ACTUADOR) REFERENCES TIPO_ACTUADOR (ID_TIPO_ACTUADOR);
ALTER TABLE ACTUADOR ADD CONSTRAINT FK_ACTUADOR_ESTADO FOREIGN KEY (FK_ID_ESTADO_DISPOSITIVO) REFERENCES ESTADO_DISPOSITIVO (ID_ESTADO_DISPOSITIVO);
ALTER TABLE ACTUADOR ADD CONSTRAINT FK_ACTUADOR_ESPACIO_TRABAJO FOREIGN KEY (FK_ID_ESPACIO_TRABAJO) REFERENCES ESPACIO_TRABAJO (ID_ESPACIO_TRABAJO);
ALTER TABLE ACTUADOR ADD CONSTRAINT FK_ACTUADOR_HORARIO_AUTOMATIZACION FOREIGN KEY (FK_ID_HORARIO_AUTOMATIZACION) REFERENCES HORARIO_AUTOMATIZACION (ID_HORARIO_AUTOMATIZACION);
ALTER TABLE ALERTA ADD CONSTRAINT FK_ALERTA_LABORATORIO FOREIGN KEY (FK_ID_LABORATORIO) REFERENCES LABORATORIO (ID_LABORATORIO);
ALTER TABLE ALERTA ADD CONSTRAINT FK_ALERTA_TIPO FOREIGN KEY (FK_ID_TIPO_ALERTA) REFERENCES TIPO_ALERTA (ID_TIPO_ALERTA);
ALTER TABLE ALERTA ADD CONSTRAINT FK_ALERTA_SENSOR FOREIGN KEY (FK_ID_SENSOR) REFERENCES SENSOR (ID_SENSOR);
ALTER TABLE ETAPA_CRECIMIENTO ADD CONSTRAINT FK_ETAPA_ESPACIO_TRABAJO FOREIGN KEY (FK_ID_ESPACIO_TRABAJO) REFERENCES ESPACIO_TRABAJO (ID_ESPACIO_TRABAJO);
ALTER TABLE LECTURA ADD CONSTRAINT FK_LECTURA_SENSOR FOREIGN KEY (FK_ID_SENSOR) REFERENCES SENSOR (ID_SENSOR);
ALTER TABLE CAMARA ADD CONSTRAINT FK_CAMARA_LABORATORIO FOREIGN KEY (FK_ID_LABORATORIO) REFERENCES LABORATORIO (ID_LABORATORIO);
ALTER TABLE CONTROLADOR_AIRE ADD CONSTRAINT FK_CONTROLADOR_LABORATORIO FOREIGN KEY (FK_ID_LABORATORIO) REFERENCES LABORATORIO (ID_LABORATORIO);
ALTER TABLE CONTROLADOR_AIRE ADD CONSTRAINT FK_CONTROLADOR_HORARIO_AUTOMATIZACION FOREIGN KEY (FK_ID_HORARIO_AUTOMATIZACION) REFERENCES HORARIO_AUTOMATIZACION (ID_HORARIO_AUTOMATIZACION);

-- DATOS INICIALES

-- Insertar roles
INSERT INTO ROL (NOMBRE_ROL, DESCRIPCION) VALUES
('ADMIN', 'Administrador del sistema con acceso completo'),
('OPERADOR', 'Usuario operativo con permisos limitados'),
('SUPERVISOR', 'Supervisor de módulos y proyectos');

-- Insertar permisos
INSERT INTO PERMISO (NOMBRE_PERMISO, ESTADO_PERMISO) VALUES
('GESTION_USUARIOS', 1),
('LECTURA_SENSORES', 1),
('CONTROL_ACTUADORES', 1);

-- Insertar permisos_rol
INSERT INTO PERMISO_ROL (FK_ID_PERMISO, FK_ID_ROL, ESTADO_PERMISO_ROL) VALUES
(1, 1, 1),
(2, 2, 1),
(3, 3, 1);

-- Insertar estados de módulo
INSERT INTO ESTADO_LABORATORIO (NOMBRE_ESTADO_LABORATORIO) VALUES
('ACTIVO'),
('ALERTA'),
('MANTENIMIENTO');

-- Insertar tipos de alerta
INSERT INTO TIPO_ALERTA (NOMBRE_TIPO_ALERTA) VALUES
('WARNING'),
('INFO'),
('SUCCESS');

-- Insertar usuarios
INSERT INTO USUARIO (USERNAME, PASSWORD, EMAIL, FK_ID_ROL) VALUES
('admin', '$2b$10$ejemploHash123456', 'admin@iot.com', 1),
('operador1', '$2b$10$ejemploHash789012', 'oper1@iot.com', 2),
('supervisor1', '$2b$10$ejemploHash345678', 'super@iot.com', 3);

-- Insertar módulos de laboratorio
INSERT INTO LABORATORIO (NOMBRE_LABORATORIO, DESCRIPCION_LABORATORIO, PK_ID_ESTADO_LABORATORIO) VALUES
('Módulo Hidroponía A', 'Sistema NFT para lechugas', 1),
('Módulo Aeroponía B', 'Cultivo de raíces suspendidas', 1),
('Invernadero Inteligente C', 'Control climático automatizado', 2);

-- Insertar usuario_módulo_laboratorio
INSERT INTO USUARIO_LABORATORIO (FK_ID_USUARIO, FK_ID_LABORATORIO) VALUES
(1, 1),
(2, 2),
(3, 3);

-- Insertar módulos
INSERT INTO MODULO (NOMBRE_MODULO, FK_ID_LABORATORIO) VALUES
('Lechugas Romana', 1),
('Hierbas Aromáticas', 2),
('Tomates Cherry', 3);

-- Insertar proyectos
INSERT INTO PROYECTO (NOMBRE_PROYECTO, FK_ID_MODULO) VALUES
('PROYECTO Vertical A', 1),
('Torre Cultivo B', 2),
('Sistema Horizontal C', 3);

-- Insertar espacios de trabajo
INSERT INTO ESPACIO_TRABAJO (NOMBRE_ESPACIO_TRABAJO, DESCRIPCION_ESPACIO_TRABAJO, FK_ID_PROYECTO) VALUES
(1, 'Lechuga Romana', 1),
(2, 'Albahaca', 2),
(3, 'Tomate Cherry', 3);

-- Insertar estados de dispositivo
INSERT INTO ESTADO_DISPOSITIVO (NOMBRE_ESTADO_DISPOSITIVO) VALUES
('HABILITADO'),
('INHABILITADO'),
('MANTENIMIENTO');

-- Insertar tipos de sensor
INSERT INTO TIPO_SENSOR (NOMBRE_TIPO_SENSOR) VALUES
('TEMPERATURA'),
('HUMEDAD'),
('PH');

-- Insertar sensores
INSERT INTO SENSOR (NOMBRE_SENSOR, UNIDAD_SENSOR, FK_ID_ESTADO_DISPOSITIVO, FK_ID_ESPACIO_TRABAJO, FK_ID_TIPO_SENSOR) VALUES
('Sensor Temp A1', '°C', 1, 1, 1),
('Sensor Humedad B2', '%', 1, 2, 2),
('Sensor PH C3', 'pH', 2, 3, 3);

-- Insertar tipos de actuador
INSERT INTO TIPO_ACTUADOR (NOMBRE_TIPO_ACTUADOR) VALUES
('RIEGO'),
('VENTILADOR'),
('ILUMINACION');

-- Insertar actuadores
INSERT INTO ACTUADOR (NOMBRE_ACTUADOR, FK_ID_TIPO_ACTUADOR, FK_ID_ESTADO_DISPOSITIVO, FK_ID_ESPACIO_TRABAJO) VALUES
('Aspersor 001', 1, 1, 1),
('Ventilador 002', 2, 1, 2),
('LED Grow 003', 3, 2, 3);

-- Insertar alertas
INSERT INTO ALERTA (FK_ID_LABORATORIO, MENSAJE_ALERTA, FK_ID_TIPO_ALERTA, FK_ID_SENSOR) VALUES
(1, 'Temperatura crítica en módulo A', 1, 1),
(2, 'Humedad óptima alcanzada', 3, 2),
(3, 'PH fuera de rango permitido', 2, 3);

-- Insertar etapas de crecimiento
INSERT INTO ETAPA_CRECIMIENTO (FK_ID_ESPACIO_TRABAJO, NOMBRE_ETAPA_CRECIMIENTO, FECHA_INICIO, FECHA_FIN) VALUES
(1, 'Germinación', '2024-01-01', '2024-01-07'),
(2, 'Crecimiento', '2024-01-08', '2024-02-08'),
(3, 'Floración', '2024-02-09', NULL);

-- Insertar lecturas
INSERT INTO LECTURA (FK_ID_SENSOR, VALOR_LECTURA) VALUES
(1, 25.50),
(2, 65.00),
(3, 6.80);

-- Insertar cámaras
INSERT INTO CAMARA (NOMBRE_CAMARA, URL_STREAM, FK_ID_LABORATORIO, ESTADO_CAMARA) VALUES
('Cámara Norte', 'rtsp://cam1.stream', 1, TRUE),
('Cámara Sur', 'rtsp://cam2.stream', 2, TRUE),
('Cámara Este', 'rtsp://cam3.stream', 3, FALSE);

-- Insertar controladores de aire
INSERT INTO CONTROLADOR_AIRE (NOMBRE_CONTROLADOR_AIRE, TEMPERATURA_OBJETIVO_CONTROLADOR_AIRE, ESTADO_CONTROLADOR_AIRE, FK_ID_LABORATORIO) VALUES
('AC Module A', 23.50, TRUE, 1),
('AC Module B', 24.00, TRUE, 2),
('AC Module C', 22.50, FALSE, 3);

-- Insertar horarios de automatización
INSERT INTO HORARIO_AUTOMATIZACION (HORA_INICIO_HORARIO_AUTOMATIZACION, HORA_FIN_HORARIO_AUTOMATIZACION, DIAS_SEMANA_HORARIO_AUTOMATIZACION, ESTADO_HORARIO_AUTOMATIZACION) VALUES
('08:00:00', '08:15:00', 'LMXJVSD', TRUE),
('12:00:00', '12:30:00', 'LMXJV', TRUE),
('18:00:00', '22:00:00', 'SD', FALSE);

-- Insertar configuraciones de sensor
-- NOTA: La tabla CONFIGURACION_SENSOR ya no existe en el esquema, por lo que se ha comentado esta inserción.
-- INSERT INTO CONFIGURACION_SENSOR (FK_ID_SENSOR, VALOR_MINIMO, VALOR_MAXIMO, CALIBRACION_AUTOMATICA) VALUES
-- (1, 20.00, 30.00, TRUE),
-- (2, 60.00, 80.00, FALSE),
-- (3, 5.50, 7.50, TRUE);


-- PROCEDIMEINTOS 

DELIMITER //

-- Procedimiento para crear usuarios con hash de contraseña
CREATE PROCEDURE crear_usuario(
    IN p_username VARCHAR(50),
    IN p_password VARCHAR(255),
    IN p_email VARCHAR(100),
    IN p_id_rol INT
)
BEGIN
    DECLARE hashed_password VARCHAR(255);
    DECLARE user_count INT;
    
    -- Verificar si el usuario ya existe
    SELECT COUNT(*) INTO user_count 
    FROM USUARIO 
    WHERE USERNAME = p_username OR EMAIL = p_email;
    
    IF user_count > 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'El usuario o email ya existe';
    ELSE
        -- Generar hash de la contraseña (en producción usar bcrypt desde la aplicación)
        SET hashed_password = SHA2(CONCAT(p_password, 'salt_seguro'), 256);
        
        -- Insertar el nuevo usuario
        INSERT INTO USUARIO (USERNAME, PASSWORD, EMAIL, FK_ID_ROL)
        VALUES (p_username, hashed_password, p_email, p_id_rol);
        
        SELECT 'Usuario creado exitosamente' AS mensaje;
    END IF;
END //

-- Procedimiento para autenticar usuarios
CREATE PROCEDURE autenticar_usuario(
    IN p_username VARCHAR(50),
    IN p_password VARCHAR(255)
)
BEGIN
    DECLARE hashed_input VARCHAR(255);
    DECLARE user_id INT;
    DECLARE user_role INT;
    DECLARE user_email VARCHAR(100);
    DECLARE stored_hash VARCHAR(255);
    
    -- Generar hash de la contraseña ingresada
    SET hashed_input = SHA2(CONCAT(p_password, 'salt_seguro'), 256);
    
    -- Buscar usuario y verificar credenciales
    SELECT 
        u.ID_USUARIO,
        u.PASSWORD,
        u.EMAIL,
        u.FK_ID_ROL,
        r.NOMBRE_ROL
    INTO 
        user_id,
        stored_hash,
        user_email,
        user_role,
        @role_name
    FROM USUARIO u
    INNER JOIN ROL r ON u.FK_ID_ROL = r.ID_ROL
    WHERE u.USERNAME = p_username;
    
    IF user_id IS NULL THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Usuario no encontrado';
    ELSEIF hashed_input != stored_hash THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'Contraseña incorrecta';
    ELSE
        -- Devolver información del usuario autenticado
        SELECT 
            user_id AS ID_USUARIO,
            p_username AS USERNAME,
            user_email AS EMAIL,
            user_role AS ID_ROL,
            @role_name AS ROL,
            'Autenticación exitosa' AS MENSAJE;
    END IF;
END //

-- Procedimiento para asignar usuarios a laboratorios
CREATE PROCEDURE asignar_usuario_laboratorio(
    IN p_id_usuario INT,
    IN p_id_LABORATORIO INT
)
BEGIN
    DECLARE user_exists INT;
    DECLARE modulo_exists INT;
    DECLARE assignment_exists INT;
    
    -- Verificar si el usuario existe
    SELECT COUNT(*) INTO user_exists 
    FROM USUARIO 
    WHERE ID_USUARIO = p_id_usuario;
    
    -- Verificar si el módulo existe
    SELECT COUNT(*) INTO modulo_exists 
    FROM LABORATORIO 
    WHERE ID_LABORATORIO = p_id_LABORATORIO;
    
    -- Verificar si la asignación ya existe
    SELECT COUNT(*) INTO assignment_exists 
    FROM USUARIO_LABORATORIO 
    WHERE FK_ID_USUARIO = p_id_usuario 
    AND FK_ID_LABORATORIO = p_id_LABORATORIO;
    
    IF user_exists = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'El usuario no existe';
    ELSEIF modulo_exists = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'El módulo de laboratorio no existe';
    ELSEIF assignment_exists > 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'El usuario ya está asignado a este laboratorio';
    ELSE
        -- Realizar la asignación
        INSERT INTO USUARIO_LABORATORIO (FK_ID_USUARIO, FK_ID_LABORATORIO)
        VALUES (p_id_usuario, p_id_LABORATORIO);
        
        SELECT 'Usuario asignado al laboratorio exitosamente' AS mensaje;
    END IF;
END //

-- PROCEDIMIENTO PARA REGISTRAR NUEVAS LECTURAS DE SENSORES
CREATE PROCEDURE REGISTRAR_LECTURA(
    IN P_ID_SENSOR INT,
    IN P_VALOR_LECTURA NUMERIC(10,2)
)
BEGIN
    DECLARE V_EXISTE_SENSOR INT DEFAULT 0;
    
    -- VERIFICAR SI EL SENSOR EXISTE
    SELECT COUNT(*) INTO V_EXISTE_SENSOR 
    FROM SENSOR 
    WHERE ID_SENSOR = P_ID_SENSOR;
    
    IF V_EXISTE_SENSOR = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'ERROR: EL SENSOR NO EXISTE';
    ELSE
        -- INSERTAR LA NUEVA LECTURA
        INSERT INTO LECTURA (FK_ID_SENSOR, VALOR_LECTURA)
        VALUES (P_ID_SENSOR, P_VALOR_LECTURA);
        
        SELECT 'LECTURA REGISTRADA EXITOSAMENTE' AS MENSAJE;
    END IF;
END //

-- PROCEDIMIENTO PARA CONSULTAR HISTORIAL DE LECTURAS POR SENSOR Y RANGO DE FECHAS
CREATE PROCEDURE OBTENER_LECTURAS_SENSOR(
    IN P_ID_SENSOR INT,
    IN P_FECHA_INICIO DATETIME,
    IN P_FECHA_FIN DATETIME
)
BEGIN
    DECLARE V_EXISTE_SENSOR INT DEFAULT 0;
    
    -- VERIFICAR SI EL SENSOR EXISTE
    SELECT COUNT(*) INTO V_EXISTE_SENSOR 
    FROM SENSOR 
    WHERE ID_SENSOR = P_ID_SENSOR;
    
    IF V_EXISTE_SENSOR = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'ERROR: EL SENSOR NO EXISTE';
    ELSE
        -- CONSULTAR LECTURAS EN EL RANGO DE FECHAS
        SELECT 
            L.ID_LECTURA,
            L.FK_ID_SENSOR,
            S.NOMBRE_SENSOR,
            L.VALOR_LECTURA,
            L.REGISTRADO_EN_LECTURA
        FROM LECTURA L
        INNER JOIN SENSOR S ON L.FK_ID_SENSOR = S.ID_SENSOR
        WHERE L.FK_ID_SENSOR = P_ID_SENSOR
        AND L.REGISTRADO_EN_LECTURA BETWEEN P_FECHA_INICIO AND P_FECHA_FIN
        ORDER BY L.REGISTRADO_EN_LECTURA DESC;
    END IF;
END //

-- PROCEDIMIENTO PARA OBTENER LA LECTURA MÁS RECIENTE DE UN SENSOR
CREATE PROCEDURE OBTENER_ULTIMA_LECTURA_SENSOR(
    IN P_ID_SENSOR INT
)
BEGIN
    DECLARE V_EXISTE_SENSOR INT DEFAULT 0;
    
    -- VERIFICAR SI EL SENSOR EXISTE
    SELECT COUNT(*) INTO V_EXISTE_SENSOR 
    FROM SENSOR 
    WHERE ID_SENSOR = P_ID_SENSOR;
    
    IF V_EXISTE_SENSOR = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'ERROR: EL SENSOR NO EXISTE';
    ELSE
        -- OBTENER LA ÚLTIMA LECTURA DEL SENSOR
        SELECT 
            L.ID_LECTURA,
            L.FK_ID_SENSOR,
            S.NOMBRE_SENSOR,
            TS.NOMBRE_TIPO_SENSOR,
            S.UNIDAD_SENSOR,
            L.VALOR_LECTURA,
            L.REGISTRADO_EN_LECTURA
        FROM LECTURA L
        INNER JOIN SENSOR S ON L.FK_ID_SENSOR = S.ID_SENSOR
        INNER JOIN TIPO_SENSOR TS ON S.FK_ID_TIPO_SENSOR = TS.ID_TIPO_SENSOR
        WHERE L.FK_ID_SENSOR = P_ID_SENSOR
        ORDER BY L.REGISTRADO_EN_LECTURA DESC
        LIMIT 1;
    END IF;
END //


-- PROCEDIMIENTO PARA CREAR ALERTAS AUTOMÁTICAMENTE
CREATE PROCEDURE GENERAR_ALERTA(
    IN P_ID_LABORATORIO INT,
    IN P_MENSAJE_ALERTA TEXT,
    IN P_ID_TIPO_ALERTA INT,
    IN P_ID_SENSOR INT
)
BEGIN
    DECLARE V_EXISTE_MODULO INT DEFAULT 0;
    DECLARE V_EXISTE_TIPO_ALERTA INT DEFAULT 0;
    DECLARE V_EXISTE_SENSOR INT DEFAULT 0;
    
    -- VERIFICAR EXISTENCIA DEL MÓDULO
    SELECT COUNT(*) INTO V_EXISTE_MODULO 
    FROM LABORATORIO 
    WHERE ID_LABORATORIO = P_ID_LABORATORIO;
    
    -- VERIFICAR EXISTENCIA DEL TIPO DE ALERTA
    SELECT COUNT(*) INTO V_EXISTE_TIPO_ALERTA 
    FROM TIPO_ALERTA 
    WHERE ID_TIPO_ALERTA = P_ID_TIPO_ALERTA;
    
    -- VERIFICAR EXISTENCIA DEL SENSOR
    SELECT COUNT(*) INTO V_EXISTE_SENSOR 
    FROM SENSOR 
    WHERE ID_SENSOR = P_ID_SENSOR;
    
    IF V_EXISTE_MODULO = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'ERROR: EL MÓDULO DE LABORATORIO NO EXISTE';
    ELSEIF V_EXISTE_TIPO_ALERTA = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'ERROR: EL TIPO DE ALERTA NO EXISTE';
    ELSEIF V_EXISTE_SENSOR = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'ERROR: EL SENSOR NO EXISTE';
    ELSE
        -- INSERTAR LA NUEVA ALERTA
        INSERT INTO ALERTA (
            FK_ID_LABORATORIO, 
            MENSAJE_ALERTA, 
            FK_ID_TIPO_ALERTA, 
            FK_ID_SENSOR
        )
        VALUES (
            P_ID_LABORATORIO,
            P_MENSAJE_ALERTA,
            P_ID_TIPO_ALERTA,
            P_ID_SENSOR
        );
        
        SELECT 'ALERTA GENERADA EXITOSAMENTE' AS MENSAJE;
    END IF;
END //

-- PROCEDIMIENTO PARA VERIFICAR UMBRALES Y GENERAR ALERTAS AUTOMÁTICAMENTE
-- NOTA: Se ha comentado este procedimiento porque la tabla CONFIGURACION_SENSOR fue eliminada del esquema.
/*
CREATE PROCEDURE VERIFICAR_UMBRAL_SENSOR(
    IN P_ID_SENSOR INT,
    IN P_VALOR_LECTURA NUMERIC(10,2)
)
BEGIN
    DECLARE V_VALOR_MINIMO NUMERIC(10,2);
    DECLARE V_VALOR_MAXIMO NUMERIC(10,2);
    DECLARE V_ID_LABORATORIO INT;
    DECLARE V_NOMBRE_SENSOR VARCHAR(100);
    DECLARE V_UNIDAD_SENSOR VARCHAR(20);
    DECLARE V_TIPO_SENSOR VARCHAR(50);
    DECLARE V_MENSAJE_ALERTA TEXT;
    DECLARE V_ID_TIPO_ALERTA INT;
    
    -- OBTENER CONFIGURACIÓN DEL SENSOR
    SELECT 
        CS.VALOR_MINIMO,
        CS.VALOR_MAXIMO,
        ML.ID_LABORATORIO,
        S.NOMBRE_SENSOR,
        S.UNIDAD,
        TS.NOMBRE_TIPO_SENSOR
    INTO 
        V_VALOR_MINIMO,
        V_VALOR_MAXIMO,
        V_ID_LABORATORIO,
        V_NOMBRE_SENSOR,
        V_UNIDAD_SENSOR,
        V_TIPO_SENSOR
    FROM CONFIGURACION_SENSOR CS
    INNER JOIN SENSOR S ON CS.FK_ID_SENSOR = S.ID_SENSOR
    INNER JOIN TIPO_SENSOR TS ON S.FK_ID_TIPO_SENSOR = TS.ID_TIPO_SENSOR
    INNER JOIN ESPACIO_TRABAJO F ON S.FK_ID_ESPACIO_TRABAJO = F.ID_ESPACIO_TRABAJO
    INNER JOIN PROYECTO E ON F.FK_ID_PROYECTO = E.ID_PROYECTO
    INNER JOIN PROYECTO P ON E.FK_ID_PROYECTO = P.ID_PROYECTO
    INNER JOIN LABORATORIO ML ON P.FK_ID_LABORATORIO = ML.ID_LABORATORIO
    WHERE CS.FK_ID_SENSOR = P_ID_SENSOR;
    
    -- VERIFICAR SI LA LECTURA ESTÁ FUERA DE RANGO
    IF P_VALOR_LECTURA < V_VALOR_MINIMO THEN
        SET V_MENSAJE_ALERTA = CONCAT(
            'ALERTA: EL SENSOR ', V_NOMBRE_SENSOR, ' (', V_TIPO_SENSOR, 
            ') REGISTRÓ UN VALOR POR DEBAJO DEL MÍNIMO PERMITIDO. ',
            'VALOR: ', P_VALOR_LECTURA, ' ', V_UNIDAD_SENSOR, 
            ' | MÍNIMO: ', V_VALOR_MINIMO, ' ', V_UNIDAD_SENSOR
        );
        SET V_ID_TIPO_ALERTA = 1; -- WARNING
        
        CALL GENERAR_ALERTA(
            V_ID_LABORATORIO,
            V_MENSAJE_ALERTA,
            V_ID_TIPO_ALERTA,
            P_ID_SENSOR
        );
        
    ELSEIF P_VALOR_LECTURA > V_VALOR_MAXIMO THEN
        SET V_MENSAJE_ALERTA = CONCAT(
            'ALERTA: EL SENSOR ', V_NOMBRE_SENSOR, ' (', V_TIPO_SENSOR, 
            ') REGISTRÓ UN VALOR POR ENCIMA DEL MÁXIMO PERMITIDO. ',
            'VALOR: ', P_VALOR_LECTURA, ' ', V_UNIDAD_SENSOR, 
            ' | MÁXIMO: ', V_VALOR_MAXIMO, ' ', V_UNIDAD_SENSOR
        );
        SET V_ID_TIPO_ALERTA = 1; -- WARNING
        
        CALL GENERAR_ALERTA(
            V_ID_LABORATORIO,
            V_MENSAJE_ALERTA,
            V_ID_TIPO_ALERTA,
            P_ID_SENSOR
        );
        
    END IF;
END //
*/

-- PROCEDIMIENTO PARA OBTENER ALERTAS ACTIVAS DE UN LABORATORIO
CREATE PROCEDURE OBTENER_ALERTAS_ACTIVAS(
    IN P_ID_LABORATORIO INT
)
BEGIN
    DECLARE V_EXISTE_MODULO INT DEFAULT 0;
    
    -- VERIFICAR EXISTENCIA DEL MÓDULO
    SELECT COUNT(*) INTO V_EXISTE_MODULO 
    FROM LABORATORIO 
    WHERE ID_LABORATORIO = P_ID_LABORATORIO;
    
    IF V_EXISTE_MODULO = 0 THEN
        SIGNAL SQLSTATE '45000' 
        SET MESSAGE_TEXT = 'ERROR: EL MÓDULO DE LABORATORIO NO EXISTE';
    ELSE
        -- CONSULTAR ALERTAS ACTIVAS (ASUMIENDO QUE NO TENEMOS CAMPO DE ESTADO, USAMOS LAS MÁS RECIENTES)
        SELECT 
            A.ID_ALERTA,
            A.FK_ID_LABORATORIO,
            ML.NOMBRE_LABORATORIO AS MODULO,
            A.MENSAJE_ALERTA,
            TA.NOMBRE_TIPO_ALERTA AS TIPO_ALERTA,
            S.NOMBRE_SENSOR AS SENSOR,
            TS.NOMBRE_TIPO_SENSOR AS TIPO_SENSOR,
            A.CREADA_EN_ALERTA
        FROM ALERTA A
        INNER JOIN LABORATORIO ML ON A.FK_ID_LABORATORIO = ML.ID_LABORATORIO
        INNER JOIN TIPO_ALERTA TA ON A.FK_ID_TIPO_ALERTA = TA.ID_TIPO_ALERTA
        INNER JOIN SENSOR S ON A.FK_ID_SENSOR = S.ID_SENSOR
        INNER JOIN TIPO_SENSOR TS ON S.FK_ID_TIPO_SENSOR = TS.ID_TIPO_SENSOR
        WHERE A.FK_ID_LABORATORIO = P_ID_LABORATORIO
        AND A.CREADA_EN_ALERTA >= DATE_SUB(NOW(), INTERVAL 24 HOUR) -- ALERTAS DE LAS ÚLTIMAS 24 HORAS
        ORDER BY A.CREADA_EN_ALERTA DESC;
    END IF;
END //

DELIMITER ;